import { IconLayers, IconZap, IconScan } from "./icons";

export const TIERS = [
  {
    code: "M",
    bracket: "[M-Arc]",
    title: "META",
    subtitle: "The Foundation Awakens",
    chapter: "01",
    Icon: IconLayers,
    hook: "Setiap legenda dimulai dengan fondasi yang tak terlihat.",
    body: "Sebelum dunia melihat produk Anda, kami mendefinisikan cetak birunya. Logo System bukan sekadar simbol, ia adalah sumpah konsistensi. Design System adalah bahasa yang akan digunakan seluruh alam semesta brand Anda. Meta ARC memastikan bahwa saat Anda melangkah, tanah di bawah kaki Anda adalah granit, bukan pasir.",
    systemLabel: "FOUNDATION SYSTEM",
    systemTagline: "The rules of your universe",
    accentRgb: "0,212,255",
    color: "#00d4ff",
    tags: [
      "Logo System",
      "Color System",
      "Typography System",
      "Design System",
      "Content Strategy",
      "Motion Design",
    ],
  },
  {
    code: "A",
    bracket: "[A-Arc]",
    title: "ALPHA",
    subtitle: "Forging the Weapon",
    chapter: "02",
    Icon: IconZap,
    hook: "Cetak biru di tangan. Sekarang saatnya menempa.",
    body: "Alpha ARC mengubah DNA yang sudah ditulis menjadi produk yang hidup. Roadmap yang terukur, template siap pakai, dan dokumentasi setajam pedang — semuanya diserahkan ke tangan Anda. Tidak ada lagi eksperimen buta. Ini adalah eksekusi yang presisi, dari nol hingga peluncuran.",
    systemLabel: "BUILD SYSTEM",
    systemTagline: "Craftsmanship at scale",
    accentRgb: "157,111,255",
    color: "#9d6fff",
    tags: [
      "Roadmap",
      "Framework",
      "Templates",
      "Playbooks",
      "Dev Documentation",
      "Portfolio Structure",
    ],
  },
  {
    code: "X",
    bracket: "[X-Arc]",
    title: "X",
    subtitle: "Ascending Beyond",
    chapter: "03",
    Icon: IconScan,
    hook: "Produk Anda sudah hidup. Kini saatnya berevolusi.",
    body: "X ARC adalah tempat aturan dilanggar dengan penuh perhitungan. Fitur eksperimental, sistem yang siap didorong ke skala tak terbatas, dan eksplorasi UI yang membuat kompetitor bertanya-tanya. Di sini, kami tidak hanya membangun produk — kami membangun legenda.",
    systemLabel: "EXPLORATION SYSTEM",
    systemTagline: "Evolving what's possible",
    accentRgb: "0,255,136",
    color: "#00ff88",
    tags: [
      "UI Experiments",
      "Interaction Concepts",
      "Visual Systems",
      "Future Layer",
      "R&D",
    ],
  },
] as const;

export const ARC_STEPS = [
  {
    l: "A",
    step: "01",
    name: "Analyze",
    verb: "Scout",
    Icon: IconScan,
    body: "Kami menyelami kebutuhan Anda lebih dalam daripada sekadar brief. Seperti pengintai, kami petakan medan, identifikasi hambatan, dan temukan celah emas yang akan diisi solusi Anda. Fase ini adalah fondasi mengapa semua yang kami bangun selalu tepat sasaran.",
    accentRgb: "0,212,255",
    color: "#00d4ff",
  },
  {
    l: "R",
    step: "02",
    name: "Refine",
    verb: "Forge",
    Icon: IconLayers,
    body: "Dengan peta yang lengkap, kami membangun — dengan presisi. Setiap keputusan visual, setiap struktur informasi, setiap baris kode ditempa mengikuti cetak biru MAX. Hasilnya bukan hanya produk yang berfungsi, tapi senjata bisnis yang elegan dan siap tempur.",
    accentRgb: "157,111,255",
    color: "#9d6fff",
  },
  {
    l: "C",
    step: "03",
    name: "Convert",
    verb: "Dominate",
    Icon: IconZap,
    body: "Membangun adalah satu bab. Memastikan menghasilkan kemenangan adalah bab berikutnya. Kami optimalkan performa, skalabilitas, dan sistem pertumbuhan agar produk Anda terus melesat — tanpa perlu dirombak ulang. Inilah saatnya Anda memimpin arena.",
    accentRgb: "240,165,0",
    color: "#f0a500",
  },
] as const;

export const LOADER_TEXT = "max arc";
